# MkDocs Configuration for Hei-DataHub Manual
site_name: Hei-DataHub Documentation
site_description: 'Official documentation for Hei-DataHub v0.57.x (beta) - A local-first TUI for managing datasets with inline editing and structured search'
site_author: Hei-DataHub Team
site_url: https://0xpix.github.io/Hei-DataHub

# Repository
repo_name: 0xpix/Hei-DataHub
repo_url: https://github.com/0xpix/Hei-DataHub
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Hei-DataHub Contributors

# Configuration
theme:
  name: simple-blog
  components:
    title: false
    preview: true
    site_name: false
  highlightjs: true
    - bash
  sidebar: true
  navigation_depth: 2
  custom_dir: docs/
  logo: assets/dark_logo_H_large.svg
  favicon: assets/dark_logo_H_large.svg

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - macros:
      include_dir: docs/_includes

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree / Navigation - Simplified structure
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: getting-started/00-welcome.md
    - Getting started: getting-started/01-getting-started.md
    - Navigation: getting-started/02-navigation.md
    - The Basics: getting-started/03-the-basics.md
  - What's New:
    - 0.57-beta "Renovation": whats-new/0.57-beta.md
    - 0.58-beta "Packaging": whats-new/0.58-beta.md
  - How-to Guides:
    - Configure GitHub Settings: how-to/04-settings.md
    - Your First Dataset: how-to/05-first-dataset.md
    - Edit Datasets: how-to/06-edit-datasets.md
    - Advanced Search: how-to/07-search-advanced.md
    - Customize Keybindings: how-to/08-customize-keybindings.md
    - Change Theme: how-to/09-change-theme.md
  - Reference:
    - UI Guide: reference/10-ui.md
    - Data & SQL: reference/11-data-and-sql.md
    - Configuration: reference/12-config.md
    - Search Syntax: reference/search-syntax.md
    - Keyboard Shortcuts: reference/keybindings.md
  - Help:
    - FAQ: help/90-faq.md
    - Troubleshooting: help/troubleshooting.md

# Extra
extra:
  version:
    provider: mike
  logo: assets/dark_logo.svg
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xpix/Hei-DataHub
  generator: false

# Additional CSS
extra_css:
  - assets/overrides.css
markdown_extensions:
  - attr_list
  - toc:
      permalink: true

# Additional JavaScript
extra_javascript:
  - assets/vim-navigation.js
  - assets/repo-url.js
