# MkDocs Configuration for Hei-DataHub Manual
site_name: Doc
site_description: 'Official documentation for Hei-DataHub v0.57.x (beta) - A local-first TUI for managing datasets with inline editing and structured search'
site_author: Hei-DataHub Team
site_url: https://0xpix.github.io/Hei-DataHub

# Repository
repo_name: 0xpix/Hei-DataHub
repo_url: https://github.com/0xpix/Hei-DataHub
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Hei-DataHub Contributors

# Configuration
theme:
  name: simple-blog
  components:
    title: false
  custom_dir: docs/
  logo: assets/dark_logo_H_large.svg
  favicon: assets/dark_logo_H_large.svg

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - macros:
      include_dir: docs/_includes

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: false
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree / Navigation - Simplified structure
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: 00-welcome.md
    - Getting started: 01-getting-started.md
    - Navigation: 02-navigation.md
    - The Basics: 03-the-basics.md
  - What's New:
    - 0.57-beta "Renovation": whats-new/0.57-beta.md
  - How-to Guides:
    - Your First Dataset: how-to/02-first-dataset.md
    - Edit Datasets: how-to/edit-datasets.md
    - Search & Filters: how-to/03-search-and-filters.md
    - Advanced Search: how-to/search-advanced.md
    - Customize Keybindings: how-to/customize-keybindings.md
    - Change Theme: how-to/change-theme.md
  - Reference:
    - UI Guide: 10-ui.md
    - Data & SQL: 11-data-and-sql.md
    - Configuration: 12-config.md
    - Search Syntax: reference/search-syntax.md
    - Keyboard Shortcuts: reference/keybindings.md
  - Help:
    - FAQ: 90-faq.md
    - Troubleshooting: troubleshooting.md

# Extra
extra:
  version:
    provider: mike
  logo: assets/dark_logo.svg
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xpix/Hei-DataHub
  generator: false

# Additional CSS
extra_css:
  - assets/overrides.css
markdown_extensions:
  - attr_list
  - toc:
      permalink: true

# Additional JavaScript
extra_javascript:
  - assets/vim-navigation.js
