name: Build Windows Binary

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - 'release/**'
      - 'fix/**'
  workflow_dispatch:
    inputs:
      version:
        description: '0.61-beta'
        required: false
        default: 'main'

permissions:
  contents: write

jobs:
  build-windows-binary:
    name: Build Windows Binary
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install UV
        run: |
          pip install uv

      - name: Create Icon
        run: |
          magick convert assets/png/Hei-datahub-logo-round.png -define icon:auto-resize=256,128,64,48,32,16 win-icon.ico

      - name: Build binary
        run: |
          .\scripts\build_windows_exe.ps1

      - name: Install Inno Setup
        run: |
          choco install innosetup

      - name: Build Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" scripts\windows_installer.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hei-DataHub-Setup
          path: |
            dist/windows/Hei-DataHub-Setup.exe

      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/windows/Hei-DataHub-Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
